# Generated by Django 4.1.4 on 2022-12-13 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('246e2448-68d7-44de-b883-5f6de1cf9ecd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
