# Generated by Django 4.1.4 on 2022-12-09 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_stream_follower_stream_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ae9f559-65f3-42f0-be73-357c7f20cc97'), editable=False, primary_key=True, serialize=False),
        ),
    ]
