 # Generated by Django 4.1.4 on 2022-12-13 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92bdfc1c-9f12-42a9-b31b-5e235461a4ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
