# Generated by Django 4.1.4 on 2022-12-13 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ed3ab99-b161-4625-966c-d726174e58c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
