# Generated by Django 4.1.4 on 2022-12-09 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_id_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73ecd358-7d2b-4b9c-9125-66b1adfd235f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
