# Generated by Django 4.1.4 on 2022-12-09 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c92adffb-de94-4bbd-a4bf-acd7c5028471'), editable=False, primary_key=True, serialize=False),
        ),
    ]
