# Generated by Django 4.1.4 on 2022-12-13 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ede65c0d-0b14-4219-ad14-2de162215391'), editable=False, primary_key=True, serialize=False),
        ),
    ]
