# Generated by Django 4.1.4 on 2022-12-12 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a431df21-feb2-4b96-822e-0768a2445177'), editable=False, primary_key=True, serialize=False),
        ),
    ]
