# Generated by Django 4.1.4 on 2022-12-13 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c6d88e8-78a0-423d-80b5-5b42a04e6841'), editable=False, primary_key=True, serialize=False),
        ),
    ]
